import React, { useState, useEffect, useCallback } from 'react'
import {
  api,
  NarrativePageData,
  NarrativeResult,
  NarrativeEmployee,
  NarrativeDriver,
} from '../services/api'
import { useDemoStore } from '../stores/demoStore'

type Tab = 'impact' | 'attrition' | 'simulation' | 'brief'

// ── Palette helpers ───────────────────────────────────────────────────────────

function dirColor(direction: string): string {
  return direction === 'risk' ? '#e07030'
    : direction === 'protective' ? '#1a8c4e'
    : direction === 'positive'   ? '#2a7ab0'
    : 'rgba(255,255,255,0.4)'
}

function pct(n: number): string { return `${(n * 100).toFixed(0)}%` }

// ── Ollama status banner ──────────────────────────────────────────────────────

function OllamaBanner({ available, model }: { available: boolean; model: string }) {
  const color = available ? '#1a8c4e' : '#c8982a'
  const bg    = available ? 'rgba(26,140,78,0.10)' : 'rgba(200,152,42,0.10)'
  const label = available ? `Ollama online — ${model}` : 'Template mode — Ollama not detected'
  const sub   = available
    ? 'Narratives generated by local LLM. Zero data leaves the perimeter.'
    : 'High-quality template narratives active. Start Ollama to enable LLM generation.'

  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 14,
      padding: '10px 18px', borderRadius: 6,
      backgroundColor: bg, border: `1px solid ${color}33`,
      marginBottom: 24,
    }}>
      <div style={{
        width: 8, height: 8, borderRadius: '50%', backgroundColor: color,
        flexShrink: 0,
        boxShadow: available ? `0 0 8px ${color}` : 'none',
      }} />
      <div>
        <div style={{ fontFamily: 'var(--fb)', fontSize: 11, fontWeight: 700,
          color, letterSpacing: '0.5px' }}>
          {label}
        </div>
        <div style={{ fontSize: 10, color: 'rgba(255,255,255,0.45)', marginTop: 2 }}>{sub}</div>
      </div>
      {!available && (
        <div style={{ marginLeft: 'auto', fontSize: 9, fontFamily: 'var(--fb)',
          color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: '1px' }}>
          docker run -d -p 11434:11434 ollama/ollama
        </div>
      )}
    </div>
  )
}

// ── Narrative panel ───────────────────────────────────────────────────────────

function NarrativePanel({
  result, loading,
}: { result: NarrativeResult | null; loading: boolean }) {
  const card: React.CSSProperties = {
    backgroundColor: 'var(--surface)', borderRadius: 'var(--radius)',
    border: '1px solid rgba(255,255,255,0.06)',
    padding: '20px 24px', marginTop: 16,
  }

  if (loading) return (
    <div style={{ ...card, display: 'flex', alignItems: 'center', gap: 12 }}>
      <div style={{
        width: 16, height: 16, borderRadius: '50%',
        border: '2px solid rgba(201,168,76,0.3)',
        borderTop: '2px solid var(--gold-light)',
        animation: 'spin 0.8s linear infinite',
      }} />
      <span style={{ fontFamily: 'var(--fb)', fontSize: 11, color: 'rgba(255,255,255,0.5)' }}>
        Generating narrative…
      </span>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )

  if (!result) return null

  const paragraphs = result.narrative.split('\n\n').filter(Boolean)

  return (
    <div style={card}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            padding: '3px 10px', borderRadius: 3, fontSize: 8, fontWeight: 700,
            letterSpacing: '1.5px', textTransform: 'uppercase', fontFamily: 'var(--fb)',
            backgroundColor: result.is_llm ? 'rgba(26,140,78,0.15)' : 'rgba(200,152,42,0.15)',
            color: result.is_llm ? '#1a8c4e' : '#c8982a',
          }}>
            {result.is_llm ? `LLM · ${result.model.split(':')[0]}` : 'Template'}
          </div>
          {result.cached && (
            <span style={{ fontSize: 9, color: 'rgba(255,255,255,0.3)', fontFamily: 'var(--fb)' }}>
              cached
            </span>
          )}
          {result.generation_ms !== undefined && (
            <span style={{ fontSize: 9, color: 'rgba(255,255,255,0.3)', fontFamily: 'var(--fb)' }}>
              {result.generation_ms}ms
            </span>
          )}
        </div>
        <div style={{ fontSize: 9, color: 'rgba(255,255,255,0.25)', fontFamily: 'var(--fb)' }}>
          {result.generated_at?.slice(0, 10)}
        </div>
      </div>

      {/* Narrative text */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
        {paragraphs.map((para, i) => (
          <p key={i} style={{
            margin: 0, fontSize: 13, lineHeight: 1.75,
            color: para.startsWith('RETENTION') || para.startsWith('RISK') || para.startsWith('PROTECTIVE') || para.startsWith('RECOMMENDED') || para.startsWith('SUGGESTED')
              ? 'rgba(255,255,255,0.55)' : 'rgba(255,255,255,0.82)',
            fontFamily: para.startsWith('RETENTION CONVERSATION') ? 'var(--fb)' : 'inherit',
            fontWeight: para.startsWith('RETENTION CONVERSATION') ? 700 : 400,
            whiteSpace: 'pre-wrap',
          }}>
            {para}
          </p>
        ))}
      </div>

      {/* Disclaimer */}
      <div style={{
        marginTop: 18, paddingTop: 14,
        borderTop: '1px solid rgba(255,255,255,0.06)',
        display: 'flex', alignItems: 'center', gap: 8,
      }}>
        <span style={{ fontSize: 10, color: 'rgba(255,255,255,0.25)', fontStyle: 'italic' }}>
          ⓘ {result.disclaimer}
        </span>
      </div>
    </div>
  )
}

// ── Driver breakdown ──────────────────────────────────────────────────────────

function DriverBreakdown({ drivers }: { drivers: NarrativeDriver[] }) {
  if (!drivers?.length) return null
  const maxContrib = Math.max(...drivers.map(d => d.contribution), 1)

  return (
    <div style={{
      backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: 6,
      border: '1px solid rgba(255,255,255,0.05)', padding: '14px 16px',
    }}>
      <div style={{ fontFamily: 'var(--fb)', fontSize: 8, letterSpacing: '1.5px',
        textTransform: 'uppercase', color: 'rgba(255,255,255,0.35)', marginBottom: 12 }}>
        Source Factors (transparency)
      </div>
      {drivers.map((d, i) => (
        <div key={i} style={{ marginBottom: 10 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
            <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.65)' }}>{d.factor}</span>
            <span style={{ fontSize: 10, color: dirColor(d.direction), fontFamily: 'var(--fb)', fontWeight: 600 }}>
              {d.value}
            </span>
          </div>
          <div style={{ height: 3, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 2 }}>
            <div style={{
              height: '100%',
              width: `${(d.contribution / maxContrib) * 100}%`,
              backgroundColor: dirColor(d.direction),
              borderRadius: 2,
            }} />
          </div>
        </div>
      ))}
    </div>
  )
}

// ── Employee selector ─────────────────────────────────────────────────────────

function EmployeeSelector({
  employees, selectedId, onSelect, label,
}: {
  employees: NarrativeEmployee[]
  selectedId: string
  onSelect: (id: string) => void
  label: string
}) {
  return (
    <div>
      <div style={{ fontFamily: 'var(--fb)', fontSize: 9, letterSpacing: '1.5px',
        textTransform: 'uppercase', color: 'rgba(255,255,255,0.4)', marginBottom: 8 }}>
        {label}
      </div>
      <select
        value={selectedId}
        onChange={e => onSelect(e.target.value)}
        style={{
          width: '100%', padding: '8px 12px', borderRadius: 4,
          backgroundColor: 'rgba(255,255,255,0.06)',
          border: '1px solid rgba(255,255,255,0.12)',
          color: 'var(--light)', fontFamily: 'var(--fb)', fontSize: 11,
          cursor: 'pointer',
        }}
      >
        {employees.map(e => (
          <option key={e.employee_id} value={e.employee_id}
            style={{ backgroundColor: '#003366' }}>
            {e.full_name} — {e.seniority_level} {e.role_title} ({e.department})
            {e.is_nexus ? ' ★' : ''}
          </option>
        ))}
      </select>
      {/* Selected employee quick stats */}
      {(() => {
        const emp = employees.find(e => e.employee_id === selectedId)
        if (!emp) return null
        return (
          <div style={{ display: 'flex', gap: 20, marginTop: 8, fontSize: 10,
            color: 'rgba(255,255,255,0.45)', fontFamily: 'var(--fb)' }}>
            <span>Impact <strong style={{ color: '#2a7ab0' }}>{emp.impact_score.toFixed(0)}</strong></span>
            <span>Attrition risk <strong style={{ color: '#e07030' }}>{pct(emp.attrition_risk)}</strong></span>
            {emp.is_nexus && <span style={{ color: 'var(--gold-light)' }}>★ Nexus</span>}
          </div>
        )
      })()}
    </div>
  )
}

// ── Generate button ───────────────────────────────────────────────────────────

function GenerateButton({ onClick, loading, label = 'Generate Explanation' }: {
  onClick: () => void; loading: boolean; label?: string
}) {
  return (
    <button onClick={onClick} disabled={loading}
      style={{
        padding: '9px 24px', borderRadius: 4, border: 'none',
        cursor: loading ? 'wait' : 'pointer',
        backgroundColor: 'var(--gold-light)', color: '#003366',
        fontFamily: 'var(--fb)', fontSize: 11, fontWeight: 700,
        letterSpacing: '1px', textTransform: 'uppercase',
        opacity: loading ? 0.7 : 1, transition: 'opacity 0.15s',
      }}>
      {loading ? 'Generating…' : label}
    </button>
  )
}

// ── Impact tab ────────────────────────────────────────────────────────────────

function ImpactTab({ data, scenario, size }: { data: NarrativePageData; scenario: string; size: string }) {
  const emps = data.top_impact_employees
  const [selectedId, setSelectedId] = useState(emps[0]?.employee_id ?? '')
  const [result, setResult]         = useState<NarrativeResult | null>(null)
  const [loading, setLoading]       = useState(false)

  const generate = useCallback(async () => {
    if (!selectedId) return
    setLoading(true)
    try {
      const r = await api.narrative.impact({ scenario, size, employee_id: selectedId, budget_pct: 0.8 })
      setResult(r)
    } finally { setLoading(false) }
  }, [selectedId, scenario, size])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div style={{
        backgroundColor: 'var(--surface)', borderRadius: 'var(--radius)',
        border: '1px solid rgba(255,255,255,0.06)', padding: '20px 24px',
      }}>
        <EmployeeSelector employees={emps} selectedId={selectedId}
          onSelect={id => { setSelectedId(id); setResult(null) }}
          label="Select employee — sorted by impact score" />
        <div style={{ marginTop: 16 }}>
          <GenerateButton onClick={generate} loading={loading}
            label="Explain Impact Score" />
        </div>
      </div>

      {result?.source_data.drivers && (
        <DriverBreakdown drivers={result.source_data.drivers as NarrativeDriver[]} />
      )}
      <NarrativePanel result={result} loading={loading} />
    </div>
  )
}

// ── Attrition tab ─────────────────────────────────────────────────────────────

function AttritionTab({ data, scenario, size }: { data: NarrativePageData; scenario: string; size: string }) {
  const emps = data.priority_employees
  const [selectedId, setSelectedId] = useState(emps[0]?.employee_id ?? '')
  const [result, setResult]         = useState<NarrativeResult | null>(null)
  const [loading, setLoading]       = useState(false)

  const generate = useCallback(async () => {
    if (!selectedId) return
    setLoading(true)
    try {
      const r = await api.narrative.attrition({ scenario, size, employee_id: selectedId, budget_pct: 0.8 })
      setResult(r)
    } finally { setLoading(false) }
  }, [selectedId, scenario, size])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div style={{
        backgroundColor: 'var(--surface)', borderRadius: 'var(--radius)',
        border: '1px solid rgba(255,255,255,0.06)', padding: '20px 24px',
      }}>
        <EmployeeSelector employees={emps} selectedId={selectedId}
          onSelect={id => { setSelectedId(id); setResult(null) }}
          label="Select employee — sorted by retention priority (risk × impact)" />
        <div style={{ marginTop: 16 }}>
          <GenerateButton onClick={generate} loading={loading}
            label="Explain Attrition Risk" />
        </div>
      </div>

      {result?.source_data.drivers && (
        <DriverBreakdown drivers={result.source_data.drivers as NarrativeDriver[]} />
      )}
      <NarrativePanel result={result} loading={loading} />
    </div>
  )
}

// ── Simulation tab ────────────────────────────────────────────────────────────

function SimulationTab({ data, scenario, size }: { data: NarrativePageData; scenario: string; size: string }) {
  const [budgetPct, setBudgetPct] = useState(0.80)
  const [result, setResult]       = useState<NarrativeResult | null>(null)
  const [loading, setLoading]     = useState(false)
  const stats = data.org_stats

  const generate = useCallback(async () => {
    setLoading(true)
    try {
      const r = await api.narrative.simulation({ scenario, size, employee_id: '', budget_pct: budgetPct })
      setResult(r)
    } finally { setLoading(false) }
  }, [budgetPct, scenario, size])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div style={{
        backgroundColor: 'var(--surface)', borderRadius: 'var(--radius)',
        border: '1px solid rgba(255,255,255,0.06)', padding: '20px 24px',
      }}>
        {/* Org context */}
        <div style={{ display: 'flex', gap: 24, marginBottom: 20, flexWrap: 'wrap' }}>
          {[
            { label: 'Employees',   value: String(stats.n_employees) },
            { label: 'Avg Impact',  value: String(stats.avg_impact)  },
            { label: 'Nexus Count', value: String(stats.nexus_count) },
            { label: 'High Risk',   value: String(stats.high_risk_count) },
          ].map(k => (
            <div key={k.label}>
              <div style={{ fontFamily: 'var(--fb)', fontSize: 8, letterSpacing: '1.5px',
                textTransform: 'uppercase', color: 'rgba(255,255,255,0.35)', marginBottom: 2 }}>
                {k.label}
              </div>
              <div style={{ fontFamily: 'var(--fd)', fontSize: 22, color: 'var(--gold-light)' }}>
                {k.value}
              </div>
            </div>
          ))}
        </div>

        {/* Budget slider */}
        <div>
          <div style={{ fontFamily: 'var(--fb)', fontSize: 9, letterSpacing: '1.5px',
            textTransform: 'uppercase', color: 'rgba(255,255,255,0.4)', marginBottom: 8 }}>
            Budget target: {pct(budgetPct)} of current spend
            &nbsp;(retaining ~{Math.round(stats.n_employees * budgetPct)} of {stats.n_employees} employees)
          </div>
          <input type="range" min={0.5} max={1.0} step={0.05}
            value={budgetPct} onChange={e => { setBudgetPct(Number(e.target.value)); setResult(null) }}
            style={{ width: '100%', accentColor: 'var(--gold-light)' }} />
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 9,
            color: 'rgba(255,255,255,0.3)', fontFamily: 'var(--fb)', marginTop: 4 }}>
            <span>50% budget</span><span>100% (no change)</span>
          </div>
        </div>
        <div style={{ marginTop: 16 }}>
          <GenerateButton onClick={generate} loading={loading}
            label="Generate Executive Summary" />
        </div>
      </div>

      {result?.source_data && (
        <div style={{
          display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 10,
        }}>
          {[
            { label: 'Headcount Retained',    value: `${result.source_data['n_retained']} / ${result.source_data['n_total']}` },
            { label: 'Impact Preserved',       value: `${Number(result.source_data['impact_preserved_pct'] ?? 0).toFixed(0)}%`  },
            { label: 'Nexus Employees Kept',   value: String(result.source_data['nexus_retained'] ?? 0)                         },
          ].map(k => (
            <div key={k.label} style={{
              backgroundColor: 'var(--surface)', borderRadius: 6,
              border: '1px solid rgba(255,255,255,0.06)', padding: '12px 16px', textAlign: 'center',
            }}>
              <div style={{ fontFamily: 'var(--fb)', fontSize: 8, letterSpacing: '1.5px',
                textTransform: 'uppercase', color: 'rgba(255,255,255,0.35)', marginBottom: 4 }}>
                {k.label}
              </div>
              <div style={{ fontFamily: 'var(--fd)', fontSize: 22, color: 'var(--gold-light)' }}>
                {k.value}
              </div>
            </div>
          ))}
        </div>
      )}
      <NarrativePanel result={result} loading={loading} />
    </div>
  )
}

// ── Manager brief tab ─────────────────────────────────────────────────────────

function BriefTab({ data, scenario, size }: { data: NarrativePageData; scenario: string; size: string }) {
  const emps = data.priority_employees
  const [selectedId, setSelectedId] = useState(emps[0]?.employee_id ?? '')
  const [result, setResult]         = useState<NarrativeResult | null>(null)
  const [loading, setLoading]       = useState(false)

  const generate = useCallback(async () => {
    if (!selectedId) return
    setLoading(true)
    try {
      const r = await api.narrative.brief({ scenario, size, employee_id: selectedId, budget_pct: 0.8 })
      setResult(r)
    } finally { setLoading(false) }
  }, [selectedId, scenario, size])

  const selected = emps.find(e => e.employee_id === selectedId)

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {/* Context banner */}
      <div style={{
        padding: '10px 16px', borderRadius: 6,
        backgroundColor: 'rgba(42,122,176,0.08)',
        border: '1px solid rgba(42,122,176,0.15)',
        fontSize: 11, color: 'rgba(255,255,255,0.55)',
      }}>
        Manager briefs are available for employees with elevated retention priority (high attrition risk ×
        high impact). All briefs are anonymized in the generation prompt — employee names are never sent to the LLM.
        Briefs are labeled for context only and do not constitute decisions.
      </div>

      <div style={{
        backgroundColor: 'var(--surface)', borderRadius: 'var(--radius)',
        border: '1px solid rgba(255,255,255,0.06)', padding: '20px 24px',
      }}>
        <EmployeeSelector employees={emps} selectedId={selectedId}
          onSelect={id => { setSelectedId(id); setResult(null) }}
          label="Select employee — high retention priority" />

        {selected && (
          <div style={{
            marginTop: 14, padding: '10px 14px', borderRadius: 6,
            backgroundColor: 'rgba(255,255,255,0.03)',
            border: '1px solid rgba(255,255,255,0.05)',
          }}>
            <div style={{ fontFamily: 'var(--fb)', fontSize: 9, letterSpacing: '1px',
              textTransform: 'uppercase', color: 'rgba(255,255,255,0.3)', marginBottom: 8 }}>
              Anonymized profile sent to LLM
            </div>
            <div style={{ fontSize: 11, color: 'rgba(255,255,255,0.6)', fontFamily: 'monospace' }}>
              [{selected.seniority_level} {selected.role_title}]-[{selected.employee_id.slice(-5).toUpperCase()}]
              &nbsp;·&nbsp;{selected.department}&nbsp;·&nbsp;
              Impact {selected.impact_score.toFixed(0)}/100&nbsp;·&nbsp;
              Risk {pct(selected.attrition_risk)}
            </div>
            <div style={{ fontSize: 9, color: 'rgba(255,255,255,0.25)', marginTop: 4, fontFamily: 'var(--fb)' }}>
              ✓ Name not included in prompt &nbsp;·&nbsp; ✓ Salary not included &nbsp;·&nbsp; ✓ Local inference only
            </div>
          </div>
        )}

        <div style={{ marginTop: 16 }}>
          <GenerateButton onClick={generate} loading={loading}
            label="Generate Manager Brief" />
        </div>
      </div>

      {result?.source_data.drivers && (
        <DriverBreakdown drivers={result.source_data.drivers as NarrativeDriver[]} />
      )}
      <NarrativePanel result={result} loading={loading} />
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function NarrativePage() {
  const { scenario, size } = useDemoStore()
  const [data, setData]    = useState<NarrativePageData | null>(null)
  const [tab, setTab]      = useState<Tab>('impact')
  const [error, setError]  = useState<string | null>(null)

  useEffect(() => {
    setData(null)
    setError(null)
    api.narrative.data(scenario, size)
      .then(setData)
      .catch(e => setError(String(e)))
  }, [scenario, size])

  const pageStyle: React.CSSProperties = {
    padding: '32px 40px', minHeight: '100vh',
    backgroundColor: 'var(--light)', color: 'var(--light)',
  }

  if (error) return (
    <div style={{ ...pageStyle, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <span style={{ color: '#e03448', fontFamily: 'var(--fb)', fontSize: 13 }}>
        Failed to load narrative data: {error}
      </span>
    </div>
  )

  if (!data) return (
    <div style={{ ...pageStyle, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <span style={{ color: 'rgba(255,255,255,0.4)', fontFamily: 'var(--fb)', fontSize: 13 }}>
        Loading narrative engine…
      </span>
    </div>
  )

  const ollama = data.ollama_status
  const stats  = data.org_stats

  const tabStyle = (t: Tab): React.CSSProperties => ({
    background: 'none', border: 'none', cursor: 'pointer',
    fontFamily: 'var(--fb)', fontSize: 9, letterSpacing: '2px',
    textTransform: 'uppercase', padding: '7px 14px', borderRadius: 3,
    color: tab === t ? 'var(--gold-light)' : 'rgba(255,255,255,0.45)',
    backgroundColor: tab === t ? 'rgba(201,168,76,0.12)' : 'transparent',
  })

  return (
    <div style={pageStyle}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontFamily: 'var(--fd)', fontSize: 28, fontWeight: 300,
          color: 'var(--light)', margin: 0, marginBottom: 4 }}>
          Decision Narrative Engine
        </h1>
        <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.45)', margin: 0 }}>
          Plain-language explanations for impact scores, attrition risk, and simulation outcomes.
          Powered by local LLM (Ollama) or high-quality deterministic templates — zero data leaves the perimeter.
        </p>
      </div>

      {/* Ollama status banner */}
      <OllamaBanner available={ollama.available} model={ollama.model} />

      {/* Hero KPIs */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 12, marginBottom: 28 }}>
        {[
          {
            label: 'LLM Status',
            value: ollama.available ? 'Online' : 'Template',
            sub:   ollama.available ? ollama.model.split(':')[0] : 'Deterministic fallback active',
            color: ollama.available ? '#1a8c4e' : '#c8982a',
          },
          {
            label: 'Employees Available',
            value: String(stats.n_employees),
            sub:   `${stats.nexus_count} nexus · ${stats.high_risk_count} high risk`,
            color: 'var(--gold-light)',
          },
          {
            label: 'PII Protection',
            value: '100%',
            sub:   'Names & salaries stripped from all prompts',
            color: '#1a8c4e',
          },
          {
            label: 'Narrative Types',
            value: '4',
            sub:   'Impact · Attrition · Simulation · Manager Brief',
            color: 'var(--gold-light)',
          },
        ].map(k => (
          <div key={k.label} style={{
            backgroundColor: 'var(--surface)', borderRadius: 'var(--radius)',
            border: '1px solid rgba(255,255,255,0.06)', padding: '16px 20px', textAlign: 'center',
          }}>
            <div style={{ fontFamily: 'var(--fb)', fontSize: 9, letterSpacing: '1.5px',
              textTransform: 'uppercase', color: 'rgba(255,255,255,0.4)', marginBottom: 6 }}>
              {k.label}
            </div>
            <div style={{ fontFamily: 'var(--fd)', fontSize: 28, color: k.color, lineHeight: 1 }}>
              {k.value}
            </div>
            <div style={{ fontSize: 10, color: 'rgba(255,255,255,0.35)', marginTop: 5 }}>{k.sub}</div>
          </div>
        ))}
      </div>

      {/* Tab bar */}
      <div style={{ display: 'flex', gap: 4, marginBottom: 24,
        borderBottom: '1px solid rgba(255,255,255,0.07)', paddingBottom: 12 }}>
        <button style={tabStyle('impact')}     onClick={() => setTab('impact')}>Impact Score</button>
        <button style={tabStyle('attrition')}  onClick={() => setTab('attrition')}>Attrition Risk</button>
        <button style={tabStyle('simulation')} onClick={() => setTab('simulation')}>Simulation</button>
        <button style={tabStyle('brief')}      onClick={() => setTab('brief')}>Manager Brief</button>
      </div>

      {/* Tab content */}
      <div style={{ maxWidth: 840 }}>
        {tab === 'impact'     && <ImpactTab     data={data} scenario={scenario} size={size} />}
        {tab === 'attrition'  && <AttritionTab  data={data} scenario={scenario} size={size} />}
        {tab === 'simulation' && <SimulationTab data={data} scenario={scenario} size={size} />}
        {tab === 'brief'      && <BriefTab      data={data} scenario={scenario} size={size} />}
      </div>
    </div>
  )
}
